#!/usr/bin/env python

import sys

if len(sys.argv) != 3:
    print("Usage: %s msgfile outfile" % sys.argv[0])
    sys.exit(2)

# Read msgfile
try:
    msgfile = open(sys.argv[1], 'r')
except:
    sys.exit("Couldn't open file %s." % sys.argv[1])

messages = msgfile.readlines()
msgfile.close()

if len(messages) < 1:
    sys.exit("No messages found.")

# Remove newlines & whitespace
for i,m in enumerate(messages):
    messages[i] = m.strip()

# Remove empty lines
messages = list(filter(None, messages))

# Write outfile
outfile = open(sys.argv[2], 'w')

outfile.write("// Automatically generated by mkmsg.py. Do not edit!\n\n")
outfile.write("#define _MESSAGE_TABLE_SIZE %d\n\n" % len(messages))

for i,m in enumerate(messages):
    outfile.write("const char _message%d[] PROGMEM = \"%s\";\n" % (i, m))

outfile.write('\n')

outfile.write("PGM_P const _message_table[_MESSAGE_TABLE_SIZE] PROGMEM =\n")
outfile.write("{\n")

for i in range(len(messages)):
    outfile.write("    _message%d,\n" % i)

outfile.write("};\n")
outfile.close()
